export default {
        READY_TO_LOAD: 'ready_to_load',
        GET_ALL_PEOPLE:'get_all_people',
        GET_TABLE_DATA: 'get_table_data',
        GET_DATA_SUMMARIES:'get_data_summaries',
        GET_DATA_INITIAL:'get_data_initial',
        SET_CURRENT_RECORD: 'set_current_record',
        SET_QUERY:'set_query',
        CLEAR_QUERY:'clear_query',
        OVERWRITE_CURRENT_RECORD:'overwrite_current_record',
        CREATE_TRANSACTION: 'create_transaction',
        CLEAR_CURRENT_RECORD: 'clear_current_record',
        REVIEW_TRANSACTION: 'review_transaction',
        LOAD_TRANSACTION: 'load_transaction',
        NULL_TRANSACTION: 'null_transaction',
        COMMIT_TABLE_DATA: 'commit_table_data',
        SEARCH_RESULT_DATASET: 'search_result_dataset',
        SET_PEOPLE: 'set_people',
        SET_VERSIONS:'set_versions',
        START_LONG_PROCESS:'start_long_process',
        END_LONG_PROCESS:'end_long_process',
        SET_APP_USER:'set_app_user',
        GET_ORGANIZATIONS:'get_organizations',
        GET_STATES:'get_states',
        GET_ORG_TYPES:'get_orgtypes',
        GET_DISBURSEMENT_FORMATS:'get_disbursement_formats',
        GET_DISBURSEMENT_TRANSMITTALS:'get_disbursement_transmittals',
        GET_CATALOG_ROWS:'get_catalog_rows'
};